# Generated by Django 2.2.9 on 2021-01-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210107_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Enter a conscious slug', null=True, unique=True, verbose_name='slug'),
        ),
    ]
