# Generated by Django 2.2.6 on 2021-03-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210313_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Время публикации генерируется автоматически', verbose_name='Время публикации'),
        ),
    ]
