# Generated by Django 2.2.6 on 2021-03-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210314_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-user'], 'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
